runtime: nodejs20
instance_class: F1
env: standard
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2



env_variables:
CONSUMER_KEY=pcPCW9woTyqlqXynSbPfyohzwppabVlTGviqYiyapwF9k1bb
CONSUMER_SECRET=NF5l8mrop2mUVHZLaJoW7J1k3U8DdXEKKQ8yg2DT2raU71s3H0fU1S0wnEMhn8Lb
DOMAIN=https://postmalarial-unfixated-cody.ngrok-free.dev
BusinessShortCode=3576709
MPESA_PASSKEY=6114fcade61b65eb6970324ff0cce80f785aac053fb12f91eb803f3fc0ca1ee9
NGROK_AUTHTOKEN=36Btz61c4NMR3DKhxQb7bjGbugA_6XAHEZL42AeQ5cj74zFUm
TILL_NUMBER=3648019 
PORT=8080
