// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaosdlpjrimppmzmrqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphb3NkbHBqcmltcHBtem1ycXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzc0MDcsImV4cCI6MjA2MzYxMzQwN30.oezP7akyCqXqVG3EJyqCF0UIWtVIWHQIGjhb0o4u1mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);